-- 已有库只允许更新注释元数据。MySQL 的 MODIFY COLUMN 会以本行定义覆盖列属性，
-- 因此必须完整保留类型、NULL、默认值和 ON UPDATE，避免注释升级意外改变资金表语义。
SET NAMES utf8mb4;

ALTER TABLE wallet_account
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '账户主键',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户主键',
    MODIFY COLUMN available_coin BIGINT NOT NULL DEFAULT 0 COMMENT '可用金币余额',
    MODIFY COLUMN version BIGINT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '账户状态',
    MODIFY COLUMN create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    COMMENT = '用户消费金币账户';

ALTER TABLE wallet_ledger
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '流水主键',
    MODIFY COLUMN ledger_no VARCHAR(64) NOT NULL COMMENT '流水编号',
    MODIFY COLUMN account_id BIGINT NOT NULL COMMENT '账户主键',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户主键',
    MODIFY COLUMN business_type VARCHAR(32) NOT NULL COMMENT '业务类型',
    MODIFY COLUMN business_no VARCHAR(64) NOT NULL COMMENT '业务单号',
    MODIFY COLUMN direction VARCHAR(16) NOT NULL COMMENT '资金方向',
    MODIFY COLUMN amount BIGINT NOT NULL COMMENT '变动金币数量',
    MODIFY COLUMN balance_after BIGINT NOT NULL COMMENT '变动后金币余额',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '流水状态',
    MODIFY COLUMN create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    COMMENT = '钱包不可变流水';

ALTER TABLE recharge_order
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '充值订单主键',
    MODIFY COLUMN order_no VARCHAR(64) NOT NULL COMMENT '充值订单号',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户主键',
    MODIFY COLUMN coin_amount BIGINT NOT NULL COMMENT '充值金币数量',
    MODIFY COLUMN paid_amount_cent BIGINT NOT NULL COMMENT '支付金额分',
    MODIFY COLUMN exchange_rate BIGINT NOT NULL COMMENT '金币兑换比例',
    MODIFY COLUMN channel VARCHAR(32) NOT NULL COMMENT '支付渠道',
    MODIFY COLUMN channel_trade_no VARCHAR(128) NULL COMMENT '渠道交易号',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '充值订单状态',
    MODIFY COLUMN paid_time DATETIME(3) NULL COMMENT '支付完成时间',
    MODIFY COLUMN create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    COMMENT = '充值订单';

ALTER TABLE gift_catalog
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '礼物主键',
    MODIFY COLUMN gift_code VARCHAR(64) NOT NULL COMMENT '礼物编码',
    MODIFY COLUMN gift_name VARCHAR(64) NOT NULL COMMENT '礼物名称',
    MODIFY COLUMN gift_icon VARCHAR(512) NOT NULL COMMENT '礼物图标地址',
    MODIFY COLUMN coin_amount BIGINT NOT NULL COMMENT '礼物单价金币',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '上架状态',
    MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '展示排序值',
    MODIFY COLUMN create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    COMMENT = '礼物目录';

ALTER TABLE gift_order
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '礼物订单主键',
    MODIFY COLUMN order_no VARCHAR(64) NOT NULL COMMENT '礼物订单号',
    MODIFY COLUMN sender_id BIGINT NOT NULL COMMENT '送礼用户主键',
    MODIFY COLUMN request_id VARCHAR(64) NOT NULL COMMENT '客户端幂等请求标识',
    MODIFY COLUMN room_id BIGINT NOT NULL COMMENT '直播间主键',
    MODIFY COLUMN anchor_id BIGINT NOT NULL COMMENT '主播用户主键',
    MODIFY COLUMN gift_id BIGINT NOT NULL COMMENT '礼物主键',
    MODIFY COLUMN gift_count INT NOT NULL COMMENT '礼物数量',
    MODIFY COLUMN coin_amount BIGINT NOT NULL COMMENT '礼物总金币',
    MODIFY COLUMN exchange_rate BIGINT NOT NULL COMMENT '金币兑换比例快照',
    MODIFY COLUMN platform_rate INT NOT NULL COMMENT '平台抽成比例万分比',
    MODIFY COLUMN platform_coin_amount BIGINT NOT NULL COMMENT '平台抽成金币',
    MODIFY COLUMN anchor_income_amount BIGINT NOT NULL COMMENT '主播收益金币',
    MODIFY COLUMN settlement_rule_version VARCHAR(32) NOT NULL COMMENT '结算规则版本',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '礼物订单状态',
    MODIFY COLUMN create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    COMMENT = '礼物订单';

ALTER TABLE anchor_income
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '收益记录主键',
    MODIFY COLUMN income_no VARCHAR(64) NOT NULL COMMENT '收益编号',
    MODIFY COLUMN gift_order_no VARCHAR(64) NOT NULL COMMENT '礼物订单号',
    MODIFY COLUMN anchor_id BIGINT NOT NULL COMMENT '主播用户主键',
    MODIFY COLUMN gross_amount BIGINT NOT NULL COMMENT '礼物毛收益金币',
    MODIFY COLUMN platform_fee BIGINT NOT NULL COMMENT '平台抽成金币',
    MODIFY COLUMN income_amount BIGINT NOT NULL COMMENT '主播净收益金币',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '收益状态',
    MODIFY COLUMN create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    COMMENT = '主播礼物收益';

ALTER TABLE outbox_event
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '发件箱记录主键',
    MODIFY COLUMN event_id VARCHAR(64) NOT NULL COMMENT '领域事件唯一标识',
    MODIFY COLUMN event_type VARCHAR(64) NOT NULL COMMENT '领域事件类型',
    MODIFY COLUMN business_id VARCHAR(64) NOT NULL COMMENT '关联业务标识',
    MODIFY COLUMN payload JSON NOT NULL COMMENT '事件负载',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '发布状态',
    MODIFY COLUMN retry_count INT NOT NULL DEFAULT 0 COMMENT '已重试次数',
    MODIFY COLUMN next_retry_at DATETIME(3) NULL COMMENT '下次重试时间',
    MODIFY COLUMN lease_owner VARCHAR(128) NULL COMMENT '发布租约持有者',
    MODIFY COLUMN lease_until DATETIME(3) NULL COMMENT '发布租约到期时间',
    MODIFY COLUMN published_at DATETIME(3) NULL COMMENT '发布确认时间',
    MODIFY COLUMN failure_reason VARCHAR(500) NULL COMMENT '最近失败原因',
    MODIFY COLUMN create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    COMMENT = '钱包领域事件发件箱';

ALTER TABLE inbox_event
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '收件箱记录主键',
    MODIFY COLUMN event_id VARCHAR(64) NOT NULL COMMENT '领域事件唯一标识',
    MODIFY COLUMN event_type VARCHAR(64) NOT NULL COMMENT '领域事件类型',
    MODIFY COLUMN business_id VARCHAR(64) NOT NULL COMMENT '关联业务标识',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '事件处理状态',
    MODIFY COLUMN processed_at DATETIME(3) NULL COMMENT '处理完成时间',
    MODIFY COLUMN failure_reason VARCHAR(500) NULL COMMENT '处理失败原因',
    MODIFY COLUMN create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    MODIFY COLUMN update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    COMMENT = '钱包领域事件收件箱';

ALTER TABLE event_replay_audit
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '重放审计主键',
    MODIFY COLUMN event_id VARCHAR(64) NOT NULL COMMENT '重放事件标识',
    MODIFY COLUMN event_type VARCHAR(64) NOT NULL COMMENT '重放事件类型',
    MODIFY COLUMN business_id VARCHAR(64) NOT NULL COMMENT '关联业务标识',
    MODIFY COLUMN operator_id BIGINT NOT NULL COMMENT '重放操作人主键',
    MODIFY COLUMN replay_reason VARCHAR(500) NOT NULL COMMENT '重放原因',
    MODIFY COLUMN replay_result VARCHAR(32) NOT NULL COMMENT '重放结果',
    MODIFY COLUMN replay_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '重放时间',
    COMMENT = '死信重放审计';
